defaultPortal: dev
portals:
  - name: dev
    portalId: 8020292
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMGNuq6hLxIEAA0ADBjEwukDII-LrwUo7ukMMhkAJ-LUTU748pJPFFXqIG4EXUbNfPX0PqNbOigAAARBAAAAeAAAAAAAAAAAgAEAAAAAAATAAMAHYAAAAAAAAAAAAABgQhkAJ-LUTYhIYnT9EbXKWXG7CEublp4_dMF7SgNuYTE
        expiresAt: '2021-06-16T17:11:34.345Z'
    personalAccessKey: >-
      CiRkOGVlNzM3Yy0wMGQ4LTQwNjgtYmRiYi04OWU0YWJiNTFlYmIQxMLpAxiPi68FKhkABeaRgg-QNdeOlU6SHx6vpQ1Ru_Zu_mzwSgNuYTE
